/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NeighborhoodsRouteImport } from './routes/neighborhoods'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIndexRouteImport } from './routes/listings.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ListingsSlugRouteImport } from './routes/listings.$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminNeighborhoodsRouteImport } from './routes/admin.neighborhoods'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as AdminListingsIndexRouteImport } from './routes/admin.listings.index'
import { Route as AdminListingsNewRouteImport } from './routes/admin.listings.new'
import { Route as AdminListingsIdEditRouteImport } from './routes/admin.listings.$id.edit'

const NeighborhoodsRoute = NeighborhoodsRouteImport.update({
  id: '/neighborhoods',
  path: '/neighborhoods',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ListingsSlugRoute = ListingsSlugRouteImport.update({
  id: '/listings/$slug',
  path: '/listings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNeighborhoodsRoute = AdminNeighborhoodsRouteImport.update({
  id: '/neighborhoods',
  path: '/neighborhoods',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsIndexRoute = AdminListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsNewRoute = AdminListingsNewRouteImport.update({
  id: '/listings/new',
  path: '/listings/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsIdEditRoute = AdminListingsIdEditRouteImport.update({
  id: '/listings/$id/edit',
  path: '/listings/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/contact': typeof ContactRoute
  '/neighborhoods': typeof NeighborhoodsRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/neighborhoods': typeof AdminNeighborhoodsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/admin/listings/': typeof AdminListingsIndexRoute
  '/admin/listings/$id/edit': typeof AdminListingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/contact': typeof ContactRoute
  '/neighborhoods': typeof NeighborhoodsRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/neighborhoods': typeof AdminNeighborhoodsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/listings': typeof ListingsIndexRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/admin/listings': typeof AdminListingsIndexRoute
  '/admin/listings/$id/edit': typeof AdminListingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRoute
  '/contact': typeof ContactRoute
  '/neighborhoods': typeof NeighborhoodsRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/neighborhoods': typeof AdminNeighborhoodsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/admin/listings/': typeof AdminListingsIndexRoute
  '/admin/listings/$id/edit': typeof AdminListingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/contact'
    | '/neighborhoods'
    | '/admin/agents'
    | '/admin/content'
    | '/admin/neighborhoods'
    | '/admin/settings'
    | '/listings/$slug'
    | '/admin/'
    | '/listings/'
    | '/admin/listings/new'
    | '/admin/listings/'
    | '/admin/listings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/contact'
    | '/neighborhoods'
    | '/admin/agents'
    | '/admin/content'
    | '/admin/neighborhoods'
    | '/admin/settings'
    | '/listings/$slug'
    | '/admin'
    | '/listings'
    | '/admin/listings/new'
    | '/admin/listings'
    | '/admin/listings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agents'
    | '/contact'
    | '/neighborhoods'
    | '/admin/agents'
    | '/admin/content'
    | '/admin/neighborhoods'
    | '/admin/settings'
    | '/listings/$slug'
    | '/admin/'
    | '/listings/'
    | '/admin/listings/new'
    | '/admin/listings/'
    | '/admin/listings/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentsRoute: typeof AgentsRoute
  ContactRoute: typeof ContactRoute
  NeighborhoodsRoute: typeof NeighborhoodsRoute
  ListingsSlugRoute: typeof ListingsSlugRoute
  ListingsIndexRoute: typeof ListingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/neighborhoods': {
      id: '/neighborhoods'
      path: '/neighborhoods'
      fullPath: '/neighborhoods'
      preLoaderRoute: typeof NeighborhoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/': {
      id: '/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/listings/$slug': {
      id: '/listings/$slug'
      path: '/listings/$slug'
      fullPath: '/listings/$slug'
      preLoaderRoute: typeof ListingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/neighborhoods': {
      id: '/admin/neighborhoods'
      path: '/neighborhoods'
      fullPath: '/admin/neighborhoods'
      preLoaderRoute: typeof AdminNeighborhoodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings/': {
      id: '/admin/listings/'
      path: '/listings'
      fullPath: '/admin/listings/'
      preLoaderRoute: typeof AdminListingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings/new': {
      id: '/admin/listings/new'
      path: '/listings/new'
      fullPath: '/admin/listings/new'
      preLoaderRoute: typeof AdminListingsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings/$id/edit': {
      id: '/admin/listings/$id/edit'
      path: '/listings/$id/edit'
      fullPath: '/admin/listings/$id/edit'
      preLoaderRoute: typeof AdminListingsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminNeighborhoodsRoute: typeof AdminNeighborhoodsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminListingsNewRoute: typeof AdminListingsNewRoute
  AdminListingsIndexRoute: typeof AdminListingsIndexRoute
  AdminListingsIdEditRoute: typeof AdminListingsIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentsRoute: AdminAgentsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminNeighborhoodsRoute: AdminNeighborhoodsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminListingsNewRoute: AdminListingsNewRoute,
  AdminListingsIndexRoute: AdminListingsIndexRoute,
  AdminListingsIdEditRoute: AdminListingsIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentsRoute: AgentsRoute,
  ContactRoute: ContactRoute,
  NeighborhoodsRoute: NeighborhoodsRoute,
  ListingsSlugRoute: ListingsSlugRoute,
  ListingsIndexRoute: ListingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
